### ISSUE TITLE
Distance metrics different from euclidian for hierarchical clustering fail

### ISSUE THREAD

**Issue by raki123** [mhoogen/ML4QS#2]
Hierarchical clustering fails when using manhattan or minkowski with specified value p as a distance metric. See the following lines in the code:
https://github.com/mhoogen/ML4QS/blob/master/PythonCode/Chapter5/Clustering.py#L307-L310
This is due to 
a) pdist taking the string 'cityblock' for manhattan distance 
b) linkage not taking additional arguments, so specifying p is not possible.
(a possible work around for b) would be:
`from scipy.spatial.distance import pdist`
`self.link = linkage(temp_dataset.as_matrix(), method=link_function, metric= lambda x,y : pdist([x,y], 'minkowski', p)[0])`
which is however significantly slower)

**Comment by mhoogen** [comment]
Well spotted. Updated it, now no longer includes the Minkowski distance but does allow usage of the Manhattan distance.
