### ISSUE TITLE
max cluster number not used

### ISSUE THREAD

**Issue by raki123** [mhoogen/ML4QS#3]
In the following line:
https://github.com/mhoogen/ML4QS/blob/master/PythonCode/crowdsignals_ch5.py#L112
the value `k` for the maximum number of clusters is not used, instead the function is always provided with input 5.
(This also explains the constant silhouette value.)

**Comment by mhoogen** [comment]
Thanks a lot for reporting this, I've fixed it. Please send me your group number.

**Comment by raki123** [comment]
No problem, we are group 30.
