### ISSUE TITLE
Reservoir matrix unlikely to be sparse

### ISSUE THREAD

**Issue by raki123** [mhoogen/ML4QS#4]
In our opinion this matrix W for the echo state network is not going to be sparse. 
https://github.com/mhoogen/ML4QS/blob/master/PythonCode/Chapter8/LearningAlgorithmsTemporal.py#L68
Is this intended? Because according to the lecture slides the matrix should be sparse.
If this is intended, why?

**Comment by mhoogen** [comment]
Agreed, this is just a very simple implementation and indeed is not necessarily a sparse matrix. We drew inspiration from an existing implementation (as referred to). Anyone can feel free to extend it of course.
