### ISSUE TITLE
Does the code is just the "Pen and Paper" code answer?

### ISSUE THREAD

**Issue by symphony2014** [mhoogen/ML4QS#8]

**Comment by mhoogen** [comment]
The code includes an implementation of nearly all techniques covered in the book. In addition, code is provided that we used to generate both the figures in the more theoretical part of the book as well as all code associated with the crowdsignals case. The code does not include answers to the pen and paper exercises as these are not coding assignments, but more theoretical questions.

**Comment by symphony2014** [comment]
@mhoogen ,thank you so much.

**Comment by mhoogen** [comment]
You're welcome
